"""make_perfmath.py - write perfmath.bas: FOR loops against the MATH, ARRAY,
SORT and MEMORY commands that do the same work on a whole array.

Same harness and output as perfguide.bas (R <id> <passes> <best ms>); passes
are elements processed, so best ms * 1000 / passes is us per element, except
the S tests (small arrays), where a pass is one sum of the whole array.
"""
import os
import make_perfguide as mp

T = []


def custom(tid, title, lines, passes):
    T.append((tid, "custom", title, passes, lines))


def loop(body):
    return ["For k = 1 To 5", "  For j = 0 To 999"] + ["    " + l for l in body] + ["  Next", "Next"]


def five(lines):
    return ["For k = 1 To 5"] + ["  " + l for l in lines] + ["Next"]


E = 5000   # 5 x 1000 elements

custom("M1a", "scale: b(j) = a(j) * 2.5 in a loop", loop(["b(j) = a(j) * 2.5"]), E)
custom("M1b", "Math Scale a(), 2.5, b()", five(["Math Scale a(), 2.5, b()"]), E)
custom("M2a", "offset: b(j) = a(j) + 7 in a loop", loop(["b(j) = a(j) + 7"]), E)
custom("M2b", "Math Add a(), 7, b()", five(["Math Add a(), 7, b()"]), E)
custom("M3a", "c(j) = a(j) * b(j) in a loop", loop(["c(j) = a(j) * b(j)"]), E)
custom("M3b", "Math C_Mul a(), b(), c()", five(["Math C_Mul a(), b(), c()"]), E)
custom("M4a", "copy: b(j) = a(j) in a loop", loop(["b(j) = a(j)"]), E)
custom("M4b", "b() = a()", five(["b() = a()"]), E)
custom("M4c", "Memory Copy Float", five(["Memory Copy Float pa%, pb%, 1000"]), E)
custom("M5a", "largest and where: IF in a loop", ["For k = 1 To 5", "  mx = a(0) : ix% = 0", "  For j = 1 To 999",
                                                   "    If a(j) > mx Then mx = a(j) : ix% = j", "  Next", "Next"], E)
custom("M5b", "mx = Math(MAX a(), ix%)", five(["mx = Math(MAX a(), ix%)"]), E)
custom("M6a", "mean in a loop", ["For k = 1 To 5", "  tot = 0", "  For j = 0 To 999", "    tot = tot + a(j)", "  Next",
                                  "  mn = tot / 1000", "Next"], E)
custom("M6b", "mn = Math(MEAN a())", five(["mn = Math(MEAN a())"]), E)
custom("M7a", "dot product in a loop", ["For k = 1 To 5", "  tot = 0", "  For j = 0 To 999", "    tot = tot + a(j) * b(j)",
                                         "  Next", "Next"], E)
custom("M7b", "tot = Math(DOTPRODUCT a(), b())", five(["tot = Math(DOTPRODUCT a(), b())"]), E)
custom("M8a", "rotate 1000 points in a loop", ["For k = 1 To 5", "  ca = Cos(0.3) : sa = Sin(0.3)", "  For j = 0 To 999",
                                                "    xo(j) = 160 + (xi(j) - 160) * ca - (yi(j) - 120) * sa",
                                                "    yo(j) = 120 + (xi(j) - 160) * sa + (yi(j) - 120) * ca",
                                                "  Next", "Next"], E)
custom("M8b", "Math V_Rotate 160, 120, 0.3, xi(), yi(), xo(), yo()",
       five(["Math V_Rotate 160, 120, 0.3, xi(), yi(), xo(), yo()"]), E)
custom("M9a", "fit to 0-239 in a loop (find min/max, then scale)",
       ["For k = 1 To 5", "  lo = a(0) : hi = a(0)", "  For j = 1 To 999", "    If a(j) < lo Then lo = a(j)",
        "    If a(j) > hi Then hi = a(j)", "  Next", "  sc = 239 / (hi - lo)", "  For j = 0 To 999",
        "    b(j) = (a(j) - lo) * sc", "  Next", "Next"], E)
custom("M9b", "Math Window a(), 0, 239, b()", five(["Math Window a(), 0, 239, b()"]), E)
custom("M10a", "clamp to 100-900 in a loop", loop(["v = a(j)", "If v < 100 Then v = 100", "If v > 900 Then v = 900",
                                                    "b(j) = v"]), E)
custom("M10b", "Math Clamp a(), 100, 900, b()", five(["Math Clamp a(), 100, 900, b()"]), E)
custom("M11a", "Shell sort of 1000 numbers in BASIC",
       ["c() = a()", "gp% = 500", "Do While gp% > 0", "  For j = gp% To 999", "    tmp = c(j) : k = j",
        "    Do While k >= gp%", "      If c(k - gp%) <= tmp Then Exit Do", "      c(k) = c(k - gp%) : k = k - gp%",
        "    Loop", "    c(k) = tmp", "  Next", "  gp% = gp% \\ 2", "Loop"], 1000)
custom("M11b", "c() = a() : Sort c()", ["c() = a()", "Sort c()"], 1000)

# small arrays: where does a MATH call start to pay?
for n in (4, 16, 64):
    arr = "s%d" % n
    custom("S%da" % n, "sum of %d elements in a loop" % n,
           ["For k = 1 To 2000", "  tot = 0", "  For j = 0 To %d" % (n - 1), "    tot = tot + %s(j)" % arr, "  Next", "Next"], 2000)
    custom("S%db" % n, "sum of %d elements with Math(SUM)" % n,
           ["For k = 1 To 2000", "  tot = Math(SUM %s())" % arr, "Next"], 2000)
custom("S4c", "s4(0) + s4(1) + s4(2) + s4(3) written out",
       ["For k = 1 To 2000", "  tot = s4(0) + s4(1) + s4(2) + s4(3)", "Next"], 2000)
custom("S0", "the empty 2000-pass loop these use", ["For k = 1 To 2000", "Next"], 2000)

HEAD = """' perfmath.bas - FOR loops against MATH, ARRAY, SORT and MEMORY commands, for
' MMBasic_Performance_Guide.  R <id> <passes> <best ms> per test.
' Generated by make_perfmath.py: edit that, not this.
"""

DECL = """Option Console Serial
Dim Float j, k, t0, dt, best, rep, tot, mx, mn, ca, sa, lo, hi, sc, v, tmp
Dim ix%, gp%, pa%, pb%
Dim Float a(999), b(999), c(999), xi(999), yi(999), xo(999), yo(999)
Dim Float s4(3), s16(15), s64(63)
For j = 0 To 999
  a(j) = ((j * 7919) Mod 1000) + 0.5 : b(j) = j / 10
  xi(j) = j Mod 320 : yi(j) = j \\ 4
Next
For j = 0 To 63 : s64(j) = j : Next
For j = 0 To 15 : s16(j) = j : Next
For j = 0 To 3 : s4(j) = j : Next
pa% = Peek(VARADDR a()) : pb% = Peek(VARADDR b())
Print "H "; MM.Device$; " "; MM.Ver; " "; MM.Info(CPUSPEED)
"""

TAIL = """Print "DONE"
Option Console Both
End

Sub Report(id$, ms, passes)
  Print "R "; id$; " "; Str$(passes); " "; Str$(ms, 0, 4)
End Sub
"""


def program():
    lines = HEAD.splitlines() + DECL.splitlines() + [""]
    for t in T:
        lines += mp.test_block(*t)
    lines += TAIL.splitlines()
    return "\r\n".join(lines) + "\r\n"


def titles():
    return {t[0]: (t[2], t[1], t[3]) for t in T}


if __name__ == "__main__":
    here = os.path.dirname(os.path.abspath(__file__))
    data = program()
    with open(os.path.join(here, "perfmath.bas"), "w", newline="") as f:
        f.write(data)
    print("perfmath.bas", len(data), "bytes", data.count("\n"), "lines", len(T), "tests")
