"""gen_gfx.py - refresh the mesh DATA block of gfx_frames.bas from Bas/3ddemo.bas.

    python gen_gfx.py            rewrite the block between the markers in place
    python gen_gfx.py --check    only report what the block would hold

The three ships (Viper, Cobra, Sidewinder) are 3ddemo.bas's own Elite meshes.
3ddemo hands its face lists to Draw3D; gfx_frames.bas draws them as wireframe
in BASIC, so each face list is turned into its set of unique edges here, once,
on the PC. Record per ship:
    Data nv, ne
    Data x, y, z        (nv times, 3ddemo's units; the program doubles them,
                         as 3ddemo does with MATH SCALE 2.0)
    Data a, b, ...      (ne pairs of vertex numbers, 0-based within the ship)
The program's NV and NE constants must equal the totals printed here.
"""
import re
import sys

SRC = r"D:/Dropbox/PicoMite/PicoMite/Bas/3ddemo.bas"
DST = __file__.replace("gen_gfx.py", "gfx_frames.bas")
SHIPS = ["Viper", "Cobra", "Sidewinder"]
BEGIN = "' ---- mesh data: generated by gen_gfx.py from Bas/3ddemo.bas ----"
END = "' ---- end of mesh data ----"


def parse():
    nums, name = {}, None
    for ln in open(SRC, encoding="latin-1").read().splitlines():
        m = re.match(r"^'(\w+) Data", ln)
        if m:
            name = m.group(1)
            nums[name] = []
            continue
        m = re.match(r"^\s*Data\s+(.*)$", ln, re.I)
        if m and name:
            nums[name] += [int(v) for v in m.group(1).split(",")]
    ships = {}
    for nm, a in nums.items():
        if len(a) < 4:
            continue
        nv, nf = a[0], a[1]
        verts = [tuple(a[4 + 3 * i:7 + 3 * i]) for i in range(nv)]
        p = 4 + 3 * nv
        counts = a[p:p + nf]
        p += nf
        edges = []
        seen = set()
        for c in counts:
            f = a[p:p + c]
            p += c
            for i in range(c):
                u, v = f[i], f[(i + 1) % c]
                key = (min(u, v), max(u, v))
                if key not in seen:
                    seen.add(key)
                    edges.append(key)
        assert p == len(a), nm
        ships[nm] = (verts, edges)
    return ships


def block(ships):
    out = [BEGIN]
    tv = te = 0
    for nm in SHIPS:
        verts, edges = ships[nm]
        tv += len(verts)
        te += len(edges)
        out.append("' %s: %d vertices, %d edges" % (nm, len(verts), len(edges)))
        out.append("Data %d, %d" % (len(verts), len(edges)))
        for i in range(0, len(verts), 5):
            out.append("Data " + ", ".join("%d,%d,%d" % v for v in verts[i:i + 5]))
        for i in range(0, len(edges), 10):
            out.append("Data " + ", ".join("%d,%d" % e for e in edges[i:i + 10]))
    out.append(END)
    return out, tv, te


def main():
    ships = parse()
    lines, tv, te = block(ships)
    print("vertices %d, edges %d (the program's NV and NE)" % (tv, te))
    for nm in SHIPS:
        v, e = ships[nm]
        ext = max(max(abs(c) for c in p) for p in v)
        print("  %-10s nv %2d  ne %2d  extent %d (doubled %d)" % (nm, len(v), len(e), ext, 2 * ext))
    if "--check" in sys.argv:
        print("\n".join(lines))
        return
    text = open(DST, encoding="latin-1").read().replace("\r\n", "\n")
    i, j = text.index(BEGIN), text.index(END) + len(END)
    text = text[:i] + "\n".join(lines) + text[j:]
    m1 = re.search(r"Const NV = (\d+), NE = (\d+)", text)
    if not m1 or int(m1.group(1)) != tv or int(m1.group(2)) != te:
        sys.exit("gfx_frames.bas: Const NV/NE do not match %d/%d" % (tv, te))
    open(DST, "w", encoding="latin-1", newline="\r\n").write(text)
    print("rewrote", DST)


if __name__ == "__main__":
    main()
