"""make_g3.py - assemble kernels.vma and write the G3 harness for each chip.

    python make_g3.py        -> g3_m0.bas (RP2040), g3_m33.bas (RP2350)

Each harness runs four kernels three ways - interpreted, as wordcode in the
VMRUN CSUB, and as C in the NATIVE CSUB - checks the three results agree and
prints the times and ratios.  The CSUB hex comes from vm_*.txt and native_*.txt
(built with armcfgen.py / armcfgen33.py)."""
import os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
OPS = ["END", "STMT", "JMP", "JZ", "JNZ", "LDL", "STL", "LAD", "LDP", "STP", "LDG", "STG",
       "LCI", "LCW", "LCF", "ADDI", "SUBI", "MULI", "ANDI", "MODI",
       "ADDF", "SUBF", "MULF", "DIVF", "CVIF", "LTI", "LEI", "GTI", "GEI", "EQI",
       "LTF", "LEF", "GTF", "GEF", "ALD", "AST", "FNXI", "FNXF", "CALL", "RET"]
OPN = {n: i for i, n in enumerate(OPS)}
SIZE = {"JMP": 2, "JZ": 2, "JNZ": 2, "LCW": 3, "FNXI": 3, "FNXF": 3, "CALL": 3}


def assemble(path):
    lines = []
    for raw in open(path):
        l = raw.split(";")[0].strip()
        if l:
            lines.append(l)
    labels, pc = {}, 0
    for l in lines:                      # pass 1: addresses
        if l.endswith(":"):
            labels[l[:-1]] = pc
            continue
        op = l.split()[0]
        pc += SIZE.get(op, 1)
    words, pc = [], 0
    for l in lines:                      # pass 2: words
        if l.endswith(":"):
            continue
        parts = l.split(None, 1)
        op = parts[0]
        args = [a.strip() for a in parts[1].split(",")] if len(parts) > 1 else []
        o = OPN[op]
        if op in ("JMP", "JZ", "JNZ"):
            words += [o, (labels[args[0]] - pc) & 0xFFFF]
        elif op == "LCW":
            v = int(args[0]) & 0xFFFFFFFF
            words += [o, v & 0xFFFF, v >> 16]
        elif op in ("FNXI", "FNXF"):
            words += [o | (int(args[0]) << 8), int(args[1]), (labels[args[2]] - pc) & 0xFFFF]
        elif op == "CALL":
            words += [o | (int(args[0]) << 8), labels[args[1]], int(args[2])]
        elif args:
            words += [o | ((int(args[0]) & 0xFF) << 8)]
        else:
            words += [o]
        pc += SIZE.get(op, 1)
    assert len(words) == pc
    return words, labels


def csub(path, decl):
    body = open(path).read().splitlines()
    assert body[0].startswith("CSUB")
    return [decl] + body[1:]


BASIC = r'''' G3 prototype harness (generated by make_g3.py - do not edit)
' Each kernel runs interpreted, as wordcode in the VMRUN CSUB and as C in the
' NATIVE CSUB; the three results must agree.
Option Default Float
Dim N%, R1%, R2%, i%, x%, cl%, chip%, E%, ok%
Dim a%(299), b%(299), c%(299)
Dim jdleap(28), leapsec(28)
Dim sys%(7), trace%(127), intr%(1), tflag%(0), vt%(1300)
Dim slots%(15), arrd%(8), vres%(3), nres%(3), ia%(3), code%(@NC@)
Dim fk(7), fa(15)
Dim JW, JH, XD, YD, RO, IO, CR, CI, MIT, CK, CK2, TOT, TOT2
fk(0) = 0 : fk(1) = 1 : fk(2) = 2 : fk(3) = 4
For i% = 1 To 28 : Read jdleap(i%), leapsec(i%) : Next i%
For i% = 0 To @NC@ : Read code%(i%) : Next i%
chip% = (Peek(WORD &HE000ED00) >> 4) And &HFFF
If chip% = &HC60 Then sys%(0) = &H40054028 Else sys%(0) = &H400B0028
sys%(1) = Peek(VARADDR intr%()) : sys%(2) = Peek(VARADDR cl%)
sys%(3) = Peek(VARADDR trace%()) : sys%(4) = Peek(VARADDR vt%()) : sys%(5) = Peek(VARADDR tflag%())
slots%(0) = Peek(VARADDR N%) : slots%(1) = Peek(VARADDR R2%)
slots%(2) = Peek(VARADDR JW) : slots%(3) = Peek(VARADDR JH) : slots%(4) = Peek(VARADDR XD)
slots%(5) = Peek(VARADDR YD) : slots%(6) = Peek(VARADDR RO) : slots%(7) = Peek(VARADDR IO)
slots%(8) = Peek(VARADDR CR) : slots%(9) = Peek(VARADDR CI) : slots%(10) = Peek(VARADDR MIT)
slots%(11) = Peek(VARADDR CK2) : slots%(12) = Peek(VARADDR TOT2)
arrd%(0) = Peek(VARADDR b%()) : arrd%(1) = 0 : arrd%(2) = 299
arrd%(3) = Peek(VARADDR jdleap()) : arrd%(4) = 0 : arrd%(5) = 28
arrd%(6) = Peek(VARADDR leapsec()) : arrd%(7) = 0 : arrd%(8) = 28
Print "G3START "; MM.Device$; " "; MM.Ver; " "; Val(MM.Info(CPUSPEED)) / 1000000; " MHz chip "; Hex$(chip%)

' K1: integer loop in a SUB with locals
N% = @N1@
t = Timer : k1 N%, R1% : ti = Timer - t
E% = @E1@ : t = Timer : VMRUN E%, code%(), slots%(), arrd%(), fk(), sys%(), vres%() : tv = Timer - t
ia%(0) = N% : t = Timer : NATIVE 1, ia%(), fa(), arrd%(), nres%() : tn = Timer - t
report "K1_intloop", ti, tv, tn, R1% = R2% And R1% = nres%(0), Str$(R1%) + " " + Str$(R2%) + " " + Str$(nres%(0))

' K2: insertion sort, array reads and writes
N% = @N2@ : x% = 12345
For i% = 0 To N% - 1 : x% = (x% * 1103515245 + 12345) And &H7FFFFFFF : a%(i%) = x% Mod 100000 : b%(i%) = a%(i%) : c%(i%) = a%(i%) : Next i%
t = Timer : k2 a%(), N% : ti = Timer - t
E% = @E2@ : t = Timer : VMRUN E%, code%(), slots%(), arrd%(), fk(), sys%(), vres%() : tv = Timer - t
arrd%(0) = Peek(VARADDR c%()) : ia%(0) = N%
t = Timer : NATIVE 2, ia%(), fa(), arrd%(), nres%() : tn = Timer - t
arrd%(0) = Peek(VARADDR b%())
ok% = 1 : For i% = 0 To N% - 1 : If a%(i%) <> b%(i%) Or a%(i%) <> c%(i%) Then ok% = 0
Next i%
For i% = 1 To N% - 1 : If a%(i%) < a%(i% - 1) Then ok% = 0
Next i%
report "K2_insertsort", ti, tv, tn, ok%, Str$(a%(0)) + " " + Str$(a%(N% - 1))

' K3: julia, without the PIXEL
JW = @JW@ : JH = @JH@ : XD = 2.5 / JW : YD = (2.5 * JH / JW) / JH : RO = -1.3 : IO = -1.22 : CR = -0.78 : CI = -0.2 : MIT = 80
CK = 0 : t = Timer : k3 JW, JH, XD, YD, RO, IO, CR, CI, MIT, CK : ti = Timer - t
E% = @E3@ : t = Timer : VMRUN E%, code%(), slots%(), arrd%(), fk(), sys%(), vres%() : tv = Timer - t
fa(0) = JW : fa(1) = JH : fa(2) = XD : fa(3) = YD : fa(4) = RO : fa(5) = IO : fa(6) = CR : fa(7) = CI : fa(8) = MIT
t = Timer : NATIVE 3, ia%(), fa(), arrd%(), nres%() : tn = Timer - t
report "K3_julia", ti, tv, tn, CK = CK2 And CK = Peek(FLOAT Peek(VARADDR nres%())), Str$(CK) + " " + Str$(CK2) + " " + Str$(Peek(FLOAT Peek(VARADDR nres%())))

' K4: findleap (the anchor's hottest SUB) called in a loop
N% = @N4@
t = Timer : k4 N%, TOT : ti = Timer - t
E% = @E4@ : t = Timer : VMRUN E%, code%(), slots%(), arrd%(), fk(), sys%(), vres%() : tv = Timer - t
ia%(0) = N% : t = Timer : NATIVE 4, ia%(), fa(), arrd%(), nres%() : tn = Timer - t
report "K4_findleap", ti, tv, tn, TOT = TOT2 And TOT = Peek(FLOAT Peek(VARADDR nres%())), Str$(TOT) + " " + Str$(TOT2)
Print "G3END"
End

Sub report k$, ti, tv, tn, ok%, detail$
  Print "G3 "; k$; " interp_ms "; Str$(ti, 0, 2); " vm_ms "; Str$(tv, 0, 2); " native_ms "; Str$(tn, 0, 2);
  Print " interp/vm "; Str$(ti / tv, 0, 2); " vm/native "; Str$(tv / tn, 0, 2);
  Print " stmts "; vres%(1); " vmstatus "; vres%(0); " check "; ok%; " ("; detail$; ")"
End Sub

Sub k1(n%, s%)
  Local i%
  s% = 0
  For i% = 1 To n%
    s% = s% + (i% And 7) * 3
    If s% > 1000000 Then s% = s% - 1000000
  Next i%
End Sub

Sub k2(a%(), n%)
  Local i%, j%, v%
  For i% = 1 To n% - 1
    v% = a%(i%)
    j% = i% - 1
    Do While j% >= 0
      If a%(j%) <= v% Then Exit Do
      a%(j% + 1) = a%(j%)
      j% = j% - 1
    Loop
    a%(j% + 1) = v%
  Next i%
End Sub

Sub k3(w, h, xd, yd, rOfs, iOfs, cRe, cIm, mit, ck)
  Local X, Y, CX, CY, Zr, Zi, COUNT, new_Zr, new_Zi
  For X = 0 To (w - 1)
    CX = X * xd + rOfs
    For Y = 0 To (h - 1)
      CY = Y * yd + iOfs
      Zr = CX
      Zi = CY
      COUNT = 0
      Do While ((COUNT <= mit) And ((Zr * Zr + Zi * Zi) < 4))
        new_Zr = Zr * Zr - Zi * Zi + cRe
        new_Zi = 2 * Zr * Zi + cIm
        Zr = new_Zr
        Zi = new_Zi
        COUNT = COUNT + 1
      Loop
      ck = ck + COUNT
    Next Y
  Next X
End Sub

Sub findleap(jday, leapsecond)
  Local i As integer
  If (jday <= jdleap(1)) Then
    leapsecond = leapsec(1)
    Exit Sub
  End If
  If (jday >= jdleap(28)) Then
    leapsecond = leapsec(28)
    Exit Sub
  End If
  For i = 1 To 27
    If (jday >= jdleap(i) And jday < jdleap(i + 1)) Then
      leapsecond = leapsec(i)
      Exit Sub
    End If
  Next i
End Sub

Sub k4(n%, tot)
  Local k%, jd, ls
  tot = 0
  For k% = 1 To n%
    jd = 2441000 + (k% Mod 17000)
    findleap jd, ls
    tot = tot + ls
  Next k%
End Sub
'''

LEAP = [(2441317.5, 10), (2441499.5, 11), (2441683.5, 12), (2442048.5, 13), (2442413.5, 14),
        (2442778.5, 15), (2443144.5, 16), (2443509.5, 17), (2443874.5, 18), (2444239.5, 19),
        (2444786.5, 20), (2445151.5, 21), (2445516.5, 22), (2446247.5, 23), (2447161.5, 24),
        (2447892.5, 25), (2448257.5, 26), (2448804.5, 27), (2449169.5, 28), (2449534.5, 29),
        (2450083.5, 30), (2450630.5, 31), (2451179.5, 32), (2453736.5, 33), (2454832.5, 34),
        (2456109.5, 35), (2457204.5, 36), (2457754.5, 37)]


def main():
    words, labels = assemble(os.path.join(HERE, "kernels.vma"))
    while len(words) % 4:
        words.append(0)
    packed = [words[i] | words[i + 1] << 16 | words[i + 2] << 32 | words[i + 3] << 48 for i in range(0, len(words), 4)]
    params = {"NC": len(packed) - 1, "E1": labels["main1"], "E2": labels["main2"], "E3": labels["main3"],
              "E4": labels["main4"], "N1": 20000, "N2": 300, "JW": 40, "JH": 30, "N4": 4000}
    print("wordcode: %d words, entries %s" % (len(words), {k: labels[k] for k in ("main1", "main2", "main3", "main4")}))
    for cpu in ("m0", "m33"):
        text = BASIC
        for k, v in params.items():
            text = text.replace("@%s@" % k, str(v))
        out = text.splitlines()
        out.append("' leap seconds (solar_eclipse.bas)")
        for jd, ls in LEAP:
            out.append("Data %s, %s" % (jd, ls))
        out.append("' wordcode, four 16-bit words to an integer")
        for i in range(0, len(packed), 6):
            out.append("Data " + ", ".join("&H%X" % v for v in packed[i:i + 6]))
        out += csub(os.path.join(HERE, "vm_%s.txt" % cpu), "CSub VMRUN integer, integer, integer, integer, float, integer, integer")
        out += csub(os.path.join(HERE, "native_%s.txt" % cpu), "CSub NATIVE integer, integer, float, integer, integer")
        open(os.path.join(HERE, "g3_%s.bas" % cpu), "w", newline="\n").write("\n".join(out) + "\n")
        print("wrote g3_%s.bas" % cpu)


if __name__ == "__main__":
    main()
