"""Assemble Bas/elite/elite.bas from the hand-written sources and the generated ship data.

  Bas/elite/src/*.bas      hand-written, concatenated in filename order (00_, 10_, ...)
  Bas/elite/data/ships.bas generated by blueprints.py, appended last (it is all DATA)

Order matters only in that the main program flow must come first and END before the SUBs,
and DATA blocks must follow.  Keep the numeric prefixes.

Usage:  python build.py            assemble
        python build.py --check    assemble and report anything that looks illegal in MMBasic
"""
import os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.normpath(os.path.join(HERE, "..", "elite", "src"))
DATA = os.path.normpath(os.path.join(HERE, "..", "elite", "data", "ships.bas"))
OUT = os.path.normpath(os.path.join(HERE, "..", "elite", "elite.bas"))

# Two lists, because the two cases differ.  A keyword or a no-argument
# builtin - one usable without parentheses - cannot be a variable or a
# parameter name: it silently breaks the enclosing definition.  A builtin
# that REQUIRES parentheses is harmless as a variable name (a variable
# called val or dir is fine) but still cannot be the name of a SUB or
# FUNCTION, which MMBasic rejects with "Invalid identifier".
RESERVED = set("""
pos timer pi date time day name scroll word as min max step to then else next loop until while wend
for do if endif end sub function local dim const global static option print input line read data restore
mode font colour color cls box circle rbox text pixel arc polygon triangle blit sprite framebuffer
math play pause inkey key keydown asc chr str hex oct bin space
error on off gosub goto return select case exit erase peek poke var save load run new list edit
rnd mm epoch cursor settick
""".split())

# Everything above, plus the parenthesised builtins, for SUB/FUNCTION names.
RESERVED_NAMES = RESERVED | set("""
distance choice field trim eof lof loc dir cwd bound val ln log exp sin cos tan sqr abs int fix sgn
instr mid val len tab atn asin acos deg rad pin port pwm sound tone left right chr asc str
""".split())

DECL = re.compile(r"^\s*(?:DIM|LOCAL|CONST|STATIC)\s+(.*)$", re.I)
SUBDEF = re.compile(r"^\s*(SUB|FUNCTION)\s+([A-Za-z_][A-Za-z0-9_]*)", re.I)
PARAMS = re.compile(r"^\s*(?:SUB|FUNCTION)\s+[A-Za-z_][A-Za-z0-9_$%!]*\s*\((.*?)\)", re.I)


def base_name(tok):
    """Strip a type suffix and any array parentheses from a declared name."""
    tok = tok.strip()
    tok = re.split(r"[(=]", tok, 1)[0].strip()
    return tok.rstrip("$%!").lower()


def declared_names(text):
    """Every name introduced by DIM / LOCAL / CONST, with its line number."""
    out = []
    for i, ln in enumerate(text.splitlines(), 1):
        code = ln.split("'")[0]
        m = DECL.match(code)
        if not m:
            continue
        body = m.group(1)
        body = re.sub(r"^\s*(INTEGER|FLOAT|STRING)\s+", "", body, flags=re.I)
        depth, cur, items = 0, "", []
        for ch in body:                      # split on commas outside parentheses
            if ch == "(":
                depth += 1
            elif ch == ")":
                depth -= 1
            if ch == "," and depth == 0:
                items.append(cur)
                cur = ""
            else:
                cur += ch
        items.append(cur)
        for it in items:
            it = re.sub(r"\s+AS\s+\w+", "", it, flags=re.I)
            n = base_name(it)
            if n:
                out.append((n, i, ln.strip()))
    return out


def check(text):
    problems = []
    lines = text.splitlines()

    # reserved words used as names
    for n, i, ln in declared_names(text):
        if n in RESERVED:
            problems.append("line %d: '%s' is a reserved word: %s" % (i, n, ln))

    # A reserved word used as a SUB/FUNCTION parameter breaks the whole
    # definition, and MMBasic then reports "Variable name" at the CALL site,
    # which is nowhere near the real fault.  Worth catching here.
    for i, ln in enumerate(lines, 1):
        m = PARAMS.match(ln.split("'")[0])
        if not m:
            continue
        for prm in m.group(1).split(","):
            prm = re.sub(r"\s+AS\s+\w+", "", prm, flags=re.I)
            nm = base_name(prm)
            if nm in RESERVED:
                problems.append("line %d: parameter '%s' is a reserved word "
                                "(the caller will fail with 'Variable name'): %s" % (i, nm, ln.strip()))

    # duplicate global declarations (suffix-insensitive); LOCALs are per-SUB so track scope
    scope, seen = "(main)", {}
    for i, ln in enumerate(lines, 1):
        code = ln.split("'")[0]
        m = SUBDEF.match(code)
        if m:
            scope = m.group(2)
            continue
        if re.match(r"^\s*END\s+(SUB|FUNCTION)", code, re.I):
            scope = "(main)"
            continue
        m = DECL.match(code)
        if not m:
            continue
        is_local = code.strip().upper().startswith("LOCAL")
        key_scope = scope if is_local else "(global)"
        for n, _, _ in declared_names(ln):
            key = (key_scope, n)
            if key in seen:
                problems.append("line %d: '%s' already declared in %s at line %d" % (i, n, key_scope, seen[key]))
            else:
                seen[key] = i

    # A SUB or FUNCTION whose own name is a builtin - MMBasic rejects the
    # definition with "Invalid identifier", which at least points at the
    # right line, unlike the parameter case.
    for i, ln in enumerate(lines, 1):
        m = SUBDEF.match(ln.split("'")[0])
        if m and m.group(2).lower().rstrip("$%!") in RESERVED_NAMES:
            problems.append("line %d: '%s' is a reserved word or builtin: %s"
                            % (i, m.group(2), ln.strip()))

    # Two definitions of the same name: MMBasic reports "Duplicate name" at
    # the second one, which is clear enough, but the build should not get
    # that far.
    seen_subs = {}
    for i, ln in enumerate(lines, 1):
        m = SUBDEF.match(ln.split("'")[0])
        if not m:
            continue
        nm = m.group(2).lower().rstrip("$%!")
        if nm in seen_subs:
            problems.append("line %d: '%s' is already defined at line %d"
                            % (i, m.group(2), seen_subs[nm]))
        else:
            seen_subs[nm] = i

    # SUB/FUNCTION name colliding with a variable name
    subs = {m.group(2).lower().rstrip("$%!") for m in (SUBDEF.match(l.split("'")[0]) for l in lines) if m}
    for n, i, ln in declared_names(text):
        if n in subs:
            problems.append("line %d: '%s' is also a SUB/FUNCTION name: %s" % (i, n, ln))

    # Unbalanced block keywords.  Keywords can appear anywhere on a line
    # (single-line FOR ... : NEXT, statements after a colon), so walk the
    # words rather than matching the start of the line, and skip string
    # literals as well as comments.  EXIT FOR / EXIT DO are not closers.
    depth = {"SUB": 0, "FUNCTION": 0, "FOR": 0, "DO": 0, "SELECT": 0}
    OPENERS = {"FOR": "FOR", "DO": "DO", "SUB": "SUB", "FUNCTION": "FUNCTION", "SELECT": "SELECT"}
    CLOSERS = {"NEXT": "FOR", "LOOP": "DO"}
    for i, ln in enumerate(lines, 1):
        c = re.sub(r'"[^"]*"', '""', ln.split("'")[0]).upper()
        words = re.findall(r"[A-Z_]+", c)
        for j, w in enumerate(words):
            prev = words[j - 1] if j else ""
            if w in CLOSERS and prev != "EXIT":
                depth[CLOSERS[w]] -= 1
            elif w in OPENERS and prev not in ("END", "EXIT"):
                # A SUB or FUNCTION definition is always the first word of its
                # line; the word also appears inside OPTION CACHE SUB and in
                # EXIT SUB, neither of which opens a block.  FOR, DO and
                # SELECT can legitimately start a statement mid-line.
                if w in ("SUB", "FUNCTION") and j != 0:
                    continue
                depth[OPENERS[w]] += 1
            elif prev == "END" and w in depth:
                depth[w] -= 1
        for k, v in depth.items():
            if v < 0:
                problems.append("line %d: more closers than openers for %s: %s" % (i, k, ln.strip()))
                depth[k] = 0
    for k, v in depth.items():
        if v:
            problems.append("unclosed %s block(s): %d" % (k, v))

    # lines longer than the console/editor is happy with
    for i, ln in enumerate(lines, 1):
        if len(ln) > 240:
            problems.append("line %d: %d characters (keep under 240)" % (i, len(ln)))
    return problems


def main():
    parts, names = [], []
    for fn in sorted(os.listdir(SRC)):
        if fn.endswith(".bas"):
            parts.append(open(os.path.join(SRC, fn), encoding="utf-8").read().rstrip("\n"))
            names.append(fn)
    body = "\n\n".join(parts)
    ships = open(DATA, encoding="utf-8").read().rstrip("\n")
    text = body + "\n\n" + "' " + "=" * 70 + "\n' ship blueprint data (generated by elite_tools/blueprints.py)\n' " + "=" * 70 + "\n" + ships + "\n"
    open(OUT, "w", newline="\n", encoding="utf-8").write(text)
    n = text.count("\n")
    print("built %s: %d lines, %d bytes from %s + ships.bas" % (OUT, n, len(text), ", ".join(names)))
    problems = check(text)
    if problems:
        print("\n%d possible problems:" % len(problems))
        for p in problems:
            print("  " + p)
    else:
        print("checks clean")
    return 1 if ("--check" in sys.argv and problems) else 0


if __name__ == "__main__":
    sys.exit(main())
