' meshview.bas - Elite Phase 1 mesh viewer and winding check for the PC3
'
' AUTOMODE = 1  unattended: for every ship, a DIAGNOSE-based winding check at three
'               orientations (each polygon's engine verdict against the blueprint's
'               stored normal), wireframe and solid timings at three distances, then END.
'               Output goes to the console; elite_tools/meshcheck.py pairs it up.
' AUTOMODE = 0  interactive: N / P next or previous ship, M render mode (wire, solid,
'               hidden-line), Z distance, R toggle spin, ESC quit.
'
' The DATA block at the end is Bas/elite/data/ships.bas, generated by blueprints.py.
OPTION EXPLICIT
OPTION BASE 0
CONST AUTOMODE = 1
CONST NSHIP = 12

DIM FLOAT v(2, 39), nrm(2, 15), q(4), vq(4), rq(4), nq(4), t0, t1, size
DIM INTEGER fc(31), host(31), fs(31), f(159), col(6), ec(31), fl(31)
DIM INTEGER nv, nf, nfv, nf0, nv0, canisters, area, bounty10, visdist, energy, speed, laser, missiles, gun, explosion
DIM INTEGER i, ship, rmode, zi, spin, zz, frames
DIM FLOAT yaw, pitch, roll, zmul(2)
DIM shipnm$ LENGTH 16, k$
col(0) = RGB(WHITE) : col(1) = RGB(GRAY) : col(2) = RGB(BLUE) : col(3) = RGB(GREEN)
col(4) = RGB(RED) : col(5) = RGB(MAGENTA) : col(6) = RGB(CYAN)
zmul(0) = 2.5 : zmul(1) = 5 : zmul(2) = 12

MODE 2
FRAMEBUFFER CREATE
FRAMEBUFFER WRITE F
Draw3D CAMERA 1, 320

IF AUTOMODE THEN
  PRINT "MESHVIEW auto  MMBasic "; MM.VER; "  CPU "; MM.INFO(CPUSPEED)
  FOR ship = 0 TO NSHIP - 1
    LoadShip ship
    PRINT "SHIP "; ship; " "; shipnm$; " nv "; nv; " nf "; nf; " nf0 "; nf0; " size "; size
    CreateShip 0
    WindingCheck ship
    Draw3D CLOSE 1
    FOR rmode = 0 TO 1
      CreateShip rmode
      FOR zi = 0 TO 2
        zz = size * zmul(zi)
        t0 = TIMER
        FOR i = 1 TO 30
          CLS
          MATH Q_EULER RAD(i * 4), RAD(i * 2 + 20), RAD(i), q()
          Draw3D ROTATE q(), 1
          Draw3D WRITE 1, 0, 0, zz, 0, rmode     ' solid needs vertex-based depth (Cobra jets)
          FRAMEBUFFER COPY F, N
        NEXT i
        t1 = (TIMER - t0) / 30
        PRINT "TIME "; ship; " "; rmode; " "; zz; " "; STR$(t1, 4, 2)
      NEXT zi
      Draw3D CLOSE 1
    NEXT rmode
  NEXT ship
  FRAMEBUFFER CLOSE
  MODE 1
  PRINT "MESHVIEW done"
  END
ENDIF

' ---------------------------------------------------------------- interactive
ship = 4 : rmode = 0 : zi = 1 : spin = 1 : frames = 0
yaw = 0.6 : pitch = -0.3 : roll = 0.2
LoadShip ship
CreateShip rmode
DO
  k$ = UCASE$(INKEY$)
  IF k$ <> "" THEN
    IF k$ = "N" OR k$ = "P" THEN
      Draw3D CLOSE 1
      IF k$ = "N" THEN ship = (ship + 1) MOD NSHIP ELSE ship = (ship + NSHIP - 1) MOD NSHIP
      LoadShip ship
      CreateShip rmode
    ELSEIF k$ = "M" THEN
      Draw3D CLOSE 1
      rmode = (rmode + 1) MOD 3
      CreateShip rmode
    ELSEIF k$ = "Z" THEN
      zi = (zi + 1) MOD 3
    ELSEIF k$ = "R" THEN
      spin = 1 - spin
    ELSEIF k$ = CHR$(27) THEN
      EXIT DO
    ENDIF
  ENDIF
  IF spin THEN yaw = yaw + 0.011 : pitch = pitch + 0.007 : roll = roll + 0.003
  zz = size * zmul(zi)
  t0 = TIMER
  CLS
  MATH Q_EULER yaw, pitch, roll, q()
  Draw3D ROTATE q(), 1
  Draw3D WRITE 1, 0, 0, zz, 0, rmode     ' depthmode = mode: 0 wire, 1 vertex-sorted solid, 2 hidden-line
  t1 = TIMER - t0
  TEXT 4, 4, shipnm$ + "  " + STR$(nv0) + "v " + STR$(nf0) + "f (" + STR$(nf) + " polys)", "LT", 7, 1, RGB(YELLOW)
  TEXT 4, 14, "mode " + MID$("wire  solid hline", rmode * 6 + 1, 5) + "  z=" + STR$(zz) + "  draw " + STR$(t1, 3, 1) + " ms", "LT", 7, 1, RGB(YELLOW)
  TEXT 4, 230, "N/P ship  M mode  Z dist  R spin  ESC", "LT", 7, 1, RGB(GRAY)
  FRAMEBUFFER COPY F, N, B
LOOP
Draw3D CLOSE 1
FRAMEBUFFER CLOSE
MODE 1
END

' ---------------------------------------------------------------- subs
SUB LoadShip(sn AS INTEGER)
  LOCAL INTEGER j, kk, acc
  SELECT CASE sn
    CASE 0 : RESTORE dat_sidewinder
    CASE 1 : RESTORE dat_viper
    CASE 2 : RESTORE dat_mamba
    CASE 3 : RESTORE dat_python
    CASE 4 : RESTORE dat_cobra_mk_3
    CASE 5 : RESTORE dat_thargoid
    CASE 6 : RESTORE dat_coriolis
    CASE 7 : RESTORE dat_missile
    CASE 8 : RESTORE dat_asteroid
    CASE 9 : RESTORE dat_canister
    CASE 10 : RESTORE dat_thargon
    CASE 11 : RESTORE dat_escape_pod
  END SELECT
  READ shipnm$, nv, nf, nfv, nf0, nv0, canisters, area, bounty10, visdist, energy, speed, laser, missiles, gun, explosion
  FOR j = 0 TO nv - 1 : READ v(0, j), v(1, j), v(2, j) : NEXT j
  FOR j = 0 TO nf - 1 : READ fc(j) : NEXT j
  FOR j = 0 TO nf - 1 : READ host(j) : NEXT j
  FOR j = 0 TO nf0 - 1 : READ nrm(0, j), nrm(1, j), nrm(2, j) : NEXT j
  FOR j = 0 TO nfv - 1 : READ f(j) : NEXT j
  acc = 0
  FOR j = 0 TO nf - 1
    fs(j) = acc : acc = acc + fc(j)
    ec(j) = 0 : fl(j) = 1 + (host(j) MOD 6)
  NEXT j
  size = 0
  FOR j = 0 TO nv0 - 1
    FOR kk = 0 TO 2
      IF ABS(v(kk, j)) > size THEN size = ABS(v(kk, j))
    NEXT kk
  NEXT j
END SUB

SUB CreateShip(rm AS INTEGER)
  IF rm = 1 THEN
    Draw3D CREATE 1, nv, nf, 1, v(), fc(), f(), col(), ec(), fl()
  ELSE
    Draw3D CREATE 1, nv, nf, 1, v(), fc(), f(), col(), ec()
  ENDIF
END SUB

' Expected visibility of every polygon from the blueprint's stored normal, then the
' engine's own verdict from DIAGNOSE (sort 0 = polygon order).  Camera is at the origin.
SUB WindingCheck(sn AS INTEGER)
  LOCAL INTEGER o, p, hf, v0, zc
  LOCAL FLOAT ex, ey, ez, ddot
  FOR o = 0 TO 2
    SELECT CASE o
      CASE 0 : MATH Q_EULER 0, 0, 0, q()
      CASE 1 : MATH Q_EULER RAD(35), RAD(-20), RAD(50), q()
      CASE 2 : MATH Q_EULER RAD(200), RAD(60), RAD(-110), q()
    END SELECT
    q(4) = 1
    Draw3D ROTATE q(), 1
    zc = size * 4
    FOR p = 0 TO nf - 1
      hf = host(p)
      MATH Q_VECTOR nrm(0, hf), nrm(1, hf), nrm(2, hf), vq()
      MATH Q_ROTATE q(), vq(), nq()
      v0 = f(fs(p))
      IF v(0, v0) = 0 AND v(1, v0) = 0 AND v(2, v0) = 0 THEN
        ex = 0 : ey = 0 : ez = zc
      ELSE
        MATH Q_VECTOR v(0, v0), v(1, v0), v(2, v0), vq()
        MATH Q_ROTATE q(), vq(), rq()
        ex = rq(1) * rq(4) : ey = rq(2) * rq(4) : ez = rq(3) * rq(4) + zc
      ENDIF
      ddot = ex * nq(1) + ey * nq(2) + ez * nq(3)
      PRINT "EXP "; sn; " "; o; " "; p; " "; ddot
    NEXT p
    PRINT "DIAG "; sn; " "; o
    Draw3D DIAGNOSE 1, 0, 0, zc, 0
  NEXT o
END SUB

' ---------------------------------------------------------------- ship data
