' sheet.bas - Elite Phase 1 contact sheet: renders every ship for a screen capture.
' Writes 4-bit BMPs of the 320x240 screen to A:/ (SAVE IMAGE), to be fetched with
' XMODEM SEND from the console (elite_tools/pc3.py grab).
'   sheet_wire.bmp    all 12 ships, wireframe, 4 x 3 grid
'   sheet_solid.bmp   all 12 ships, solid
'   sheet_big.bmp     Python, Missile, Thargoid, Coriolis close up, wireframe
'   cobra_wire.bmp    Cobra Mk III close up, wireframe
'   cobra_solid.bmp   Cobra Mk III close up, solid
'   cobra_hline.bmp   Cobra Mk III close up, hidden-line
' The DATA block at the end is Bas/elite/data/ships.bas, generated by blueprints.py.
OPTION EXPLICIT
OPTION BASE 0
CONST NSHIP = 12

DIM FLOAT v(2, 39), nrm(2, 15), q(4), size
DIM INTEGER fc(31), host(31), f(159), col(6), ec(31), fl(31)
DIM INTEGER nv, nf, nfv, nf0, nv0, canisters, area, bounty10, visdist, energy, speed, laser, missiles, gun, explosion
DIM INTEGER i, ship, rmode, zz, sx, sy, wx, wy, cell
DIM shipnm$ LENGTH 16
col(0) = RGB(WHITE) : col(1) = RGB(GRAY) : col(2) = RGB(BLUE) : col(3) = RGB(GREEN)
col(4) = RGB(RED) : col(5) = RGB(MAGENTA) : col(6) = RGB(CYAN)

MODE 2
FRAMEBUFFER CREATE
FRAMEBUFFER WRITE F
Draw3D CAMERA 1, 320

FOR rmode = 0 TO 1
  CLS
  FOR ship = 0 TO NSHIP - 1
    LoadShip ship
    CreateShip rmode
    ' 4 x 3 grid of 80 x 80 cells; the ship's largest coordinate maps to 30 px
    cell = ship
    sx = 40 + 80 * (cell MOD 4)
    sy = 30 + 78 * (cell \ 4)
    zz = size * 320 \ 30
    wx = (sx - 160) * zz \ 320
    wy = -(sy - 120) * zz \ 320
    MATH Q_EULER RAD(35), RAD(-25), RAD(15), q()
    Draw3D ROTATE q(), 1
    Draw3D WRITE 1, wx, wy, zz, 0, rmode
    TEXT sx, sy + 33, shipnm$, "CT", 7, 1, RGB(YELLOW)
    Draw3D CLOSE 1
  NEXT ship
  TEXT 160, 238, "Elite meshes on Draw3D - " + MID$("wireframe solid", rmode * 10 + 1, 9), "CB", 7, 1, RGB(GRAY)
  FRAMEBUFFER COPY F, N
  IF rmode = 0 THEN SAVE IMAGE "A:/sheet_wire.bmp" ELSE SAVE IMAGE "A:/sheet_solid.bmp"
NEXT rmode

' 2 x 2 close-ups of the ships that carry sliver lines, plus the station (wireframe)
CLS
FOR i = 0 TO 3
  ship = VAL(MID$("3 7 5 6", i * 2 + 1, 1))
  LoadShip ship
  CreateShip 0
  sx = 80 + 160 * (i MOD 2)
  sy = 60 + 120 * (i \ 2)
  zz = size * 320 \ 52
  wx = (sx - 160) * zz \ 320
  wy = -(sy - 120) * zz \ 320
  MATH Q_EULER RAD(40), RAD(-30), RAD(20), q()
  Draw3D ROTATE q(), 1
  Draw3D WRITE 1, wx, wy, zz, 0, 0
  TEXT sx, sy + 50, shipnm$, "CT", 7, 1, RGB(YELLOW)
  Draw3D CLOSE 1
NEXT i
FRAMEBUFFER COPY F, N
SAVE IMAGE "A:/sheet_big.bmp"

' Cobra close-ups
LoadShip 4
FOR rmode = 0 TO 2
  CreateShip rmode
  CLS
  MATH Q_EULER RAD(30), RAD(-20), RAD(10), q()
  Draw3D ROTATE q(), 1
  zz = size * 3
  Draw3D WRITE 1, 0, 0, zz, 0, rmode     ' depthmode = mode: 0 wire, 1 vertex-sorted solid, 2 hidden-line
  TEXT 4, 4, shipnm$ + "  " + MID$("wireframe solid     hidden-line", rmode * 10 + 1, 10), "LT", 7, 1, RGB(YELLOW)
  FRAMEBUFFER COPY F, N
  IF rmode = 0 THEN SAVE IMAGE "A:/cobra_wire.bmp"
  IF rmode = 1 THEN SAVE IMAGE "A:/cobra_solid.bmp"
  IF rmode = 2 THEN SAVE IMAGE "A:/cobra_hline.bmp"
  Draw3D CLOSE 1
NEXT rmode

FRAMEBUFFER CLOSE
MODE 1
PRINT "SHEET done"
END

SUB LoadShip(sn AS INTEGER)
  LOCAL INTEGER j, kk
  SELECT CASE sn
    CASE 0 : RESTORE dat_sidewinder
    CASE 1 : RESTORE dat_viper
    CASE 2 : RESTORE dat_mamba
    CASE 3 : RESTORE dat_python
    CASE 4 : RESTORE dat_cobra_mk_3
    CASE 5 : RESTORE dat_thargoid
    CASE 6 : RESTORE dat_coriolis
    CASE 7 : RESTORE dat_missile
    CASE 8 : RESTORE dat_asteroid
    CASE 9 : RESTORE dat_canister
    CASE 10 : RESTORE dat_thargon
    CASE 11 : RESTORE dat_escape_pod
  END SELECT
  READ shipnm$, nv, nf, nfv, nf0, nv0, canisters, area, bounty10, visdist, energy, speed, laser, missiles, gun, explosion
  FOR j = 0 TO nv - 1 : READ v(0, j), v(1, j), v(2, j) : NEXT j
  FOR j = 0 TO nf - 1 : READ fc(j) : NEXT j
  FOR j = 0 TO nf - 1 : READ host(j) : NEXT j
  FOR j = 0 TO nf0 - 1 : READ nrm(0, j), nrm(1, j), nrm(2, j) : NEXT j
  FOR j = 0 TO nfv - 1 : READ f(j) : NEXT j
  FOR j = 0 TO nf - 1 : ec(j) = 0 : fl(j) = 1 + (host(j) MOD 6) : NEXT j
  size = 0
  FOR j = 0 TO nv0 - 1
    FOR kk = 0 TO 2
      IF ABS(v(kk, j)) > size THEN size = ABS(v(kk, j))
    NEXT kk
  NEXT j
END SUB

SUB CreateShip(rm AS INTEGER)
  IF rm = 1 THEN
    Draw3D CREATE 1, nv, nf, 1, v(), fc(), f(), col(), ec(), fl()
  ELSE
    Draw3D CREATE 1, nv, nf, 1, v(), fc(), f(), col(), ec()
  ENDIF
END SUB

' ---------------------------------------------------------------- ship data
